variables:
  CI_BUILD_ARCHS: "linux/amd64,linux/arm/v7"
  CI_BUILD_IMAGE: "registry.gitlab.com/r1chjames/public-docker-images:buildx"
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

docker-build-master:
  image: $CI_BUILD_IMAGE
  stage: build
  services:
    - docker:dind
  before_script:
    - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes 
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker buildx create --use
    - docker buildx build -t "$CI_REGISTRY_IMAGE" 
      --platform "$CI_BUILD_ARCHS" --cache-from "$CI_REGISTRY_IMAGE"
      --build-arg BUILDKIT_INLINE_CACHE=1 .
    - docker push "$CI_REGISTRY_IMAGE" 
  only:
    - master

docker-build:
  image: $CI_BUILD_IMAGE
  stage: build
  services:
    - docker:dind
  before_script:
    - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes 
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker buildx create --use
    - docker buildx build -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" 
      --platform "$CI_BUILD_ARCHS" --cache-from "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
      --build-arg BUILDKIT_INLINE_CACHE=1 .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
  except:
    - master
