variables:
  CI_BUILD_ARCHS: "linux/amd64"
  CI_BUILD_IMAGE: "jdrouet/docker-with-buildx:stable"
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

docker-build-master:
  image: $CI_BUILD_IMAGE
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker buildx create --use
    - docker buildx build --platform $CI_BUILD_ARCHS -t "$CI_REGISTRY_IMAGE:latest" .
  only:
    - master

docker-build:
  image: $CI_BUILD_IMAGE
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker buildx create --use
    - docker buildx build --platform $CI_BUILD_ARCHS -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
  except:
    - master
