{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "aquarium-controller.serviceAccountName" . }}
  labels:
{{ include "aquarium-controller.labels" . | indent 4 }}
{{- end -}}
